			<h1>コンテンツ管理</h1>
			
			<ul>
<!--				<li class="menu2 menu_selected"><a href="/contents/?md=list" title="表示">表示</a></li>-->
				<li class="menu2"><a href="/contents/?md=select" title="スマイルセレクト">ｽﾏｲﾙｾﾚｸﾄ</a></li>
				<li class="menu2"><a href="/contents/?md=youtube" title="YouTube">YouTube</a></li>
				<li class="menu2"><a href="/contents/?md=info" title="更新情報">更新情報</a></li>
<!--				<li class="menu2"><a href="/contents/?md=review" title="お客様の声">お客様の声</a></li>-->
			</ul>
			
			<div>
			
				<form method="post" action="/contents/" class="js_unsubmit">
					<fieldset>
						<table>
							<tbody>
								<tr>
									<th>初期物件表示件数</th>
									<td>
										
									</td>
								</tr>
								<tr>
									<th>ｽﾏｲﾙｾﾚｸﾄスライドスピード</th>
									<td>

									</td>
								</tr>
								<tr>
									<th>あと○○円の表示</th>
									<td>

									</td>
								</tr>
								<tr>
									<th>TOPページYouTube</th>
									<td><input name="" type="text" style="width:500px;" value="" /></td>
								</tr>
							</tbody>
						</table>
						<input type="submit" name="regist" value="登録" class="formbtn" />
					</fieldset>
				</form>
				
			</div>
