
  <div class="left clear">
    <nav>
      <ul class="nav">
        <li class="nav01_on border"><a href="/item/" title="物件管理">物件管理</a></li>
        <li class="nav02 border"><a href="/member/" title="会員管理">会員管理</a></li>
        <li class="nav03 border"><a href="/contents/" title="コンテンツ管理">コンテンツ管理</a></li>
        <li class="nav04 border"><a href="/master/" title="マスタ管理">マスタ管理</a></li>
      </ul>
    </nav>
  </div>