
  <div class="right">
    <h2 class="PageTitle page01">物件管理</h2>
    <div class="tab_wrap clear">
      <ul class="tab">
        <li class="tab_on"><a href="/item/">物件一覧</a></li>
        <li class="tab_off"><a href="/item/">物件登録</a></li>
        <li class="tab_off"><a href="/item/">集計・解析</a></li>
      </ul>
    </div>
    <div class="cnt_wrap">
      <div class="cnt_title clear w260">
        <h3>物件一覧</h3>
<!--        <input type="button" value="追加" id="js_add" class="btn_add btn_style_01" />-->
      </div>
      <table class="table_style">
        <thead>
          <tr><td>No.</td><td>物件名</td><td>住所</td><td>価格</td><td class="btn_tbl_with">状態</td><td class="btn_tbl_with">編集</td><td class="btn_tbl_with">削除</td></tr>
        </thead>
        <tbody>
          <tr><td>1163</td><td><a href="" target="_blank">春日市上白水８丁目　中古一戸建て</a></td><td>福岡県春日市上白水8丁目31番地</td><td>1,998万円</td><td>販</td><td><input type="button" value="編集" class="btn_edit btn_style_02" rel="regist" /></td><td><input type="button" value="削除" class="btn_delete btn_style_02" /></td></tr>
        </tbody>
      </table>
    </div>
  </div>